import { boldMinValue, addRank, sortByAll } from "./utils";

let chartTypeViewData: ChartTypeData[] = [
  {
    line_acc_plus: {val: "10.80", bold: false},
    line_acc: {val: "55.40", bold: false},
    bar_acc_plus: {val: "1.96", bold: false},
    bar_acc: {val: "50.98", bold: false},
    pie_acc_plus: {val: "0.00", bold: false},
    pie_acc: {val: "49.70", bold: false},
    area_acc_plus: {val: "1.17", bold: false},
    area_acc: {val: "47.92", bold: false},
    box_acc_plus: {val: "8.50", bold: false},
    box_acc: {val: "53.75", bold: false},
    radar_acc_plus: {val: "0.25", bold: false},
    radar_acc: {val: "49.00", bold: false},
    scatter_acc_plus: {val: "3.33", bold: false},
    scatter_acc: {val: "49.00", bold: false},
    node_acc_plus: {val: "15.50", bold: false},
    node_acc: {val: "55.75", bold: false},
    combination_acc_plus: {val: "5.13", bold: false},
    combination_acc: {val: "52.44", bold: false},
    all_acc_plus: {val: "3.79", bold: false},
    all_acc: {val: "51.26", bold: false},
    model: "VisualGLM",
    link: "https://arxiv.org/abs/2105.13290",
  },
  {
    line_acc_plus: {val: "7.40", bold: false},
    line_acc: {val: "49.85", bold: false},
    bar_acc_plus: {val: "10.62", bold: false},
    bar_acc: {val: "49.88", bold: false},
    pie_acc_plus: {val: "4.50", bold: false},
    pie_acc: {val: "51.85", bold: false},
    area_acc_plus: {val: "6.00", bold: false},
    area_acc: {val: "49.67", bold: false},
    box_acc_plus: {val: "11.33", bold: false},
    box_acc: {val: "52.08", bold: false},
    radar_acc_plus: {val: "11.88", bold: false},
    radar_acc: {val: "51.81", bold: false},
    scatter_acc_plus: {val: "4.17", bold: false},
    scatter_acc: {val: "45.50", bold: false},
    node_acc_plus: {val: "8.50", bold: false},
    node_acc: {val: "46.00", bold: false},
    combination_acc_plus: {val: "3.63", bold: false},
    combination_acc: {val: "50.63", bold: false},
    all_acc_plus: {val: "8.11", bold: false},
    all_acc: {val: "50.11", bold: false},
    model: "Shikra",
    link: "https://arxiv.org/abs/2306.15195",
  },
  {
    line_acc_plus: {val: "24.40", bold: false},
    line_acc: {val: "62.15", bold: false},
    bar_acc_plus: {val: "15.04", bold: false},
    bar_acc: {val: "56.33", bold: false},
    pie_acc_plus: {val: "19.10", bold: false},
    pie_acc: {val: "58.90", bold: false},
    area_acc_plus: {val: "4.33", bold: false},
    area_acc: {val: "48.50", bold: false},
    box_acc_plus: {val: "7.33", bold: false},
    box_acc: {val: "50.08", bold: false},
    radar_acc_plus: {val: "2.00", bold: false},
    radar_acc: {val: "47.50", bold: false},
    scatter_acc_plus: {val: "12.50", bold: false},
    scatter_acc: {val: "55.50", bold: false},
    node_acc_plus: {val: "9.00", bold: false},
    node_acc: {val: "54.25", bold: false},
    combination_acc_plus: {val: "2.38", bold: false},
    combination_acc: {val: "47.19", bold: false},
    all_acc_plus: {val: "12.49", bold: false},
    all_acc: {val: "54.46", bold: false},
    model: "InstructBLIP",
    link: "https://arxiv.org/abs/2305.06500",
  },
  {
    line_acc_plus: {val: "10.50", bold: false},
    line_acc: {val: "54.30", bold: false},
    bar_acc_plus: {val: "14.58", bold: false},
    bar_acc: {val: "56.27", bold: false},
    pie_acc_plus: {val: "17.90", bold: false},
    pie_acc: {val: "57.20", bold: false},
    area_acc_plus: {val: "12.50", bold: false},
    area_acc: {val: "55.33", bold: false},
    box_acc_plus: {val: "9.67", bold: false},
    box_acc: {val: "53.08", bold: false},
    radar_acc_plus: {val: "16.00", bold: false},
    radar_acc: {val: "55.13", bold: false},
    scatter_acc_plus: {val: "14.33", bold: false},
    scatter_acc: {val: "56.42", bold: false},
    node_acc_plus: {val: "16.00", bold: false},
    node_acc: {val: "55.50", bold: false},
    combination_acc_plus: {val: "6.13", bold: false},
    combination_acc: {val: "51.13", bold: false},
    all_acc_plus: {val: "13.30", bold: false},
    all_acc: {val: "55.22", bold: false},
    model: "CogVLM",
    link: "https://arxiv.org/abs/2311.03079",
  },
  {
    line_acc_plus: {val: "16.00", bold: false},
    line_acc: {val: "55.70", bold: false},
    bar_acc_plus: {val: "20.42", bold: false},
    bar_acc: {val: "57.38", bold: false},
    pie_acc_plus: {val: "21.50", bold: false},
    pie_acc: {val: "55.60", bold: false},
    area_acc_plus: {val: "4.50", bold: false},
    area_acc: {val: "51.17", bold: false},
    box_acc_plus: {val: "14.50", bold: false},
    box_acc: {val: "54.42", bold: false},
    radar_acc_plus: {val: "15.00", bold: false},
    radar_acc: {val: "53.50", bold: false},
    scatter_acc_plus: {val: "12.00", bold: false},
    scatter_acc: {val: "54.08", bold: false},
    node_acc_plus: {val: "8.50", bold: false},
    node_acc: {val: "54.00", bold: false},
    combination_acc_plus: {val: "5.13", bold: false},
    combination_acc: {val: "51.25", bold: false},
    all_acc_plus: {val: "15.49", bold: false},
    all_acc: {val: "55.70", bold: false},
    model: "Internlm-XComposer",
    link: "https://arxiv.org/abs/2309.15112",
  },
  {
    line_acc_plus: {val: "18.40", bold: false},
    line_acc: {val: "55.35", bold: false},
    bar_acc_plus: {val: "15.54", bold: false},
    bar_acc: {val: "53.40", bold: false},
    pie_acc_plus: {val: "23.40", bold: false},
    pie_acc: {val: "53.30", bold: false},
    area_acc_plus: {val: "12.00", bold: false},
    area_acc: {val: "53.00", bold: false},
    box_acc_plus: {val: "8.17", bold: false},
    box_acc: {val: "51.25", bold: false},
    radar_acc_plus: {val: "19.00", bold: false},
    radar_acc: {val: "54.50", bold: false},
    scatter_acc_plus: {val: "17.17", bold: false},
    scatter_acc: {val: "53.75", bold: false},
    node_acc_plus: {val: "31.00", bold: false},
    node_acc: {val: "62.75", bold: false},
    combination_acc_plus: {val: "25.88", bold: false},
    combination_acc: {val: "58.50", bold: false},
    all_acc_plus: {val: "17.89", bold: false},
    all_acc: {val: "54.30", bold: false},
    model: "SPHINX",
    link: "https://arxiv.org/abs/2311.07575",
  },
  {
    line_acc_plus: {val: "29.60", bold: false},
    line_acc: {val: "62.80", bold: false},
    bar_acc_plus: {val: "17.35", bold: false},
    bar_acc: {val: "57.33", bold: false},
    pie_acc_plus: {val: "24.90", bold: false},
    pie_acc: {val: "61.05", bold: false},
    area_acc_plus: {val: "6.17", bold: false},
    area_acc: {val: "52.42", bold: false},
    box_acc_plus: {val: "10.67", bold: false},
    box_acc: {val: "53.58", bold: false},
    radar_acc_plus: {val: "17.63", bold: false},
    radar_acc: {val: "56.69", bold: false},
    scatter_acc_plus: {val: "22.00", bold: false},
    scatter_acc: {val: "58.58", bold: false},
    node_acc_plus: {val: "33.00", bold: false},
    node_acc: {val: "41.00", bold: false},
    combination_acc_plus: {val: "28.00", bold: false},
    combination_acc: {val: "61.44", bold: false},
    all_acc_plus: {val: "20.24", bold: false},
    all_acc: {val: "57.85", bold: false},
    model: "BLIP2",
    link: "https://arxiv.org/abs/2301.12597",
  },
  {
    line_acc_plus: {val: "28.90", bold: false},
    line_acc: {val: "56.35", bold: false},
    bar_acc_plus: {val: "19.35", bold: false},
    bar_acc: {val: "54.50", bold: false},
    pie_acc_plus: {val: "22.10", bold: false},
    pie_acc: {val: "57.50", bold: false},
    area_acc_plus: {val: "16.50", bold: false},
    area_acc: {val: "57.25", bold: false},
    box_acc_plus: {val: "13.33", bold: false},
    box_acc: {val: "52.75", bold: false},
    radar_acc_plus: {val: "25.00", bold: false},
    radar_acc: {val: "58.50", bold: false},
    scatter_acc_plus: {val: "28.50", bold: false},
    scatter_acc: {val: "56.25", bold: false},
    node_acc_plus: {val: "25.50", bold: false},
    node_acc: {val: "37.25", bold: false},
    combination_acc_plus: {val: "26.38", bold: false},
    combination_acc: {val: "53.69", bold: false},
    all_acc_plus: {val: "22.26", bold: false},
    all_acc: {val: "55.18", bold: false},
    model: "ChartLlama",
    link: "https://arxiv.org/abs/2311.16483",
  },
  {
    line_acc_plus: {val: "26.70", bold: false},
    line_acc: {val: "52.80", bold: false},
    bar_acc_plus: {val: "21.54", bold: false},
    bar_acc: {val: "50.21", bold: false},
    pie_acc_plus: {val: "20.20", bold: false},
    pie_acc: {val: "48.40", bold: false},
    area_acc_plus: {val: "21.67", bold: false},
    area_acc: {val: "50.25", bold: false},
    box_acc_plus: {val: "24.67", bold: false},
    box_acc: {val: "52.67", bold: false},
    radar_acc_plus: {val: "25.88", bold: false},
    radar_acc: {val: "52.25", bold: false},
    scatter_acc_plus: {val: "28.17", bold: false},
    scatter_acc: {val: "53.92", bold: false},
    node_acc_plus: {val: "15.50", bold: false},
    node_acc: {val: "39.00", bold: false},
    combination_acc_plus: {val: "27.13", bold: false},
    combination_acc: {val: "54.25", bold: false},
    all_acc_plus: {val: "23.55", bold: false},
    all_acc: {val: "51.08", bold: false},
    model: "MiniGPT-v2",
    link: "https://arxiv.org/abs/2310.09478",
  },
  {
    line_acc_plus: {val: "34.40", bold: false},
    line_acc: {val: "60.00", bold: false},
    bar_acc_plus: {val: "24.73", bold: false},
    bar_acc: {val: "54.58", bold: false},
    pie_acc_plus: {val: "19.10", bold: false},
    pie_acc: {val: "46.70", bold: false},
    area_acc_plus: {val: "26.83", bold: false},
    area_acc: {val: "57.67", bold: false},
    box_acc_plus: {val: "25.67", bold: false},
    box_acc: {val: "54.92", bold: false},
    radar_acc_plus: {val: "28.63", bold: false},
    radar_acc: {val: "58.63", bold: false},
    scatter_acc_plus: {val: "26.00", bold: false},
    scatter_acc: {val: "55.58", bold: false},
    node_acc_plus: {val: "33.50", bold: false},
    node_acc: {val: "48.00", bold: false},
    combination_acc_plus: {val: "27.38", bold: false},
    combination_acc: {val: "55.38", bold: false},
    all_acc_plus: {val: "26.39", bold: false},
    all_acc: {val: "54.91", bold: false},
    model: "LLaVA-v1.5",
    link: "https://arxiv.org/abs/2310.03744",
  },
  {
    line_acc_plus: {val: "37.50", bold: false},
    line_acc: {val: "64.20", bold: false},
    bar_acc_plus: {val: "24.73", bold: false},
    bar_acc: {val: "57.33", bold: false},
    pie_acc_plus: {val: "26.10", bold: false},
    pie_acc: {val: "57.05", bold: false},
    area_acc_plus: {val: "21.33", bold: false},
    area_acc: {val: "55.17", bold: false},
    box_acc_plus: {val: "25.83", bold: false},
    box_acc: {val: "56.67", bold: false},
    radar_acc_plus: {val: "26.50", bold: false},
    radar_acc: {val: "58.63", bold: false},
    scatter_acc_plus: {val: "24.17", bold: false},
    scatter_acc: {val: "55.75", bold: false},
    node_acc_plus: {val: "28.50", bold: false},
    node_acc: {val: "54.75", bold: false},
    combination_acc_plus: {val: "27.50", bold: false},
    combination_acc: {val: "57.94", bold: false},
    all_acc_plus: {val: "26.78", bold: false},
    all_acc: {val: "57.93", bold: false},
    model: "mPLUG-Owl-bloomz",
    link: "https://arxiv.org/abs/2304.14178",
  },
  {
    line_acc_plus: {val: "41.00", bold: false},
    line_acc: {val: "69.00", bold: false},
    bar_acc_plus: {val: "20.96", bold: false},
    bar_acc: {val: "57.77", bold: false},
    pie_acc_plus: {val: "40.00", bold: false},
    pie_acc: {val: "67.70", bold: false},
    area_acc_plus: {val: "28.83", bold: false},
    area_acc: {val: "63.17", bold: false},
    box_acc_plus: {val: "24.17", bold: false},
    box_acc: {val: "57.50", bold: false},
    radar_acc_plus: {val: "35.00", bold: false},
    radar_acc: {val: "63.63", bold: false},
    scatter_acc_plus: {val: "19.50", bold: false},
    scatter_acc: {val: "56.75", bold: false},
    node_acc_plus: {val: "18.50", bold: false},
    node_acc: {val: "55.50", bold: false},
    combination_acc_plus: {val: "25.50", bold: false},
    combination_acc: {val: "58.63", bold: false},
    all_acc_plus: {val: "28.18", bold: false},
    all_acc: {val: "61.25", bold: false},
    model: "Qwen-VL-Chat",
    link: "https://arxiv.org/abs/2308.12966",
  },
  {
    line_acc_plus: {val: "44.00", bold: false},
    line_acc: {val: "N/A", bold: false},
    bar_acc_plus: {val: "45.00", bold: false},
    bar_acc: {val: "N/A", bold: false},
    pie_acc_plus: {val: "57.00", bold: false},
    pie_acc: {val: "N/A", bold: false},
    area_acc_plus: {val: "45.00", bold: false},
    area_acc: {val: "N/A", bold: false},
    box_acc_plus: {val: "30.00", bold: false},
    box_acc: {val: "N/A", bold: false},
    radar_acc_plus: {val: "40.00", bold: false},
    radar_acc: {val: "N/A", bold: false},
    scatter_acc_plus: {val: "51.67", bold: false},
    scatter_acc: {val: "N/A", bold: false},
    node_acc_plus: {val: "70.00", bold: false},
    node_acc: {val: "N/A", bold: false},
    combination_acc_plus: {val: "56.25", bold: false},
    combination_acc: {val: "N/A", bold: false},
    all_acc_plus: {val: "46.95", bold: false},
    all_acc: {val: "N/A", bold: false},
    model: "ERNIE",
    link: "https://yiyan.baidu.com",
  },
  {
    line_acc_plus: {val: "74.00", bold: false},
    line_acc: {val: "N/A", bold: false},
    bar_acc_plus: {val: "41.54", bold: false},
    bar_acc: {val: "N/A", bold: false},
    pie_acc_plus: {val: "63.00", bold: false},
    pie_acc: {val: "N/A", bold: false},
    area_acc_plus: {val: "33.30", bold: false},
    area_acc: {val: "N/A", bold: false},
    box_acc_plus: {val: "46.67", bold: false},
    box_acc: {val: "N/A", bold: false},
    radar_acc_plus: {val: "57.50", bold: false},
    radar_acc: {val: "N/A", bold: false},
    scatter_acc_plus: {val: "70.00", bold: false},
    scatter_acc: {val: "N/A", bold: false},
    node_acc_plus: {val: "100.00", bold: false},
    node_acc: {val: "N/A", bold: false},
    combination_acc_plus: {val: "56.25", bold: false},
    combination_acc: {val: "N/A", bold: false},
    all_acc_plus: {val: "54.39", bold: false},
    all_acc: {val: "N/A", bold: false},
    model: "GPT-4V",
    link: "https://openai.com/research/gpt-4",
  },
];

chartTypeViewData = sortByAll(chartTypeViewData);
addRank(chartTypeViewData);
boldMinValue(chartTypeViewData);

export { chartTypeViewData };
